### ISSUE TITLE
add surface field from expression does not work with boolean operators

### ISSUE THREAD

**Issue by pletzer** [gregvonkuster/galaxy-csg#30]
The following expression 

(z/4.)_(sqrt(x__2+y_*2) > 1 or (z > 2))

fails with error

Traceback (most recent call last):
  File "/var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/tools/csg/icqsol_add_surface_field_from_expression.py", line 42, in <module>
    args.location)
  File "build/bdist.linux-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 300, in addSurfaceFieldFromExpressionToVtkPolyData
  File "<string>", line 1
    (z/4.)_(sqrt(x__2+y_*2) **gt** 1 or (z **gt** 2))
                                 ^
SyntaxError: invalid syntax

**Comment by pletzer** [comment]
Note: star symbol and greater symbols were mangled in the above

**Comment by pletzer** [comment]
Checked that the expression is valid in python

``` python
from math import *
def f(x, y, z): return (z/4.)*(sqrt(x**2+y**2) > 1 or (z > 2))
print f(0, 0, 4)
```

works

**Comment by pletzer** [comment]
icqsol test with Boolean expression passes... so problem must be on the galaxy-csg (?)

```
Start 58: testAddSurfaceFieldFromBooleanExpression
```

58: Test command: /Users/pletzer/anaconda/bin/python "/Users/pletzer/icqsol/examples/addSurfaceFieldFromExpression.py" "--expression" "(z/4.)_(sqrt(x__2+y_*2) > 1 or (z > 2))" "--name" "my_field" "--input" "testPrimitiveCylinder.ply" "--output" "testPrimitiveCylinderWithBooleanField.vtk" "--ascii"
58: Test timeout computed to be: 9.99988e+06
1/1 Test #58: testAddSurfaceFieldFromBooleanExpression ...   Passed    2.05 sec

**Comment by pletzer** [comment]
I'm getting the error when I use "**gt**" in place of ">" 

``` python
def f(x, y, z): return (z/4.)*(sqrt(x**2+y**2) __gt__ 1 or (z > 2))
f(0, 0, 4)
```

```
  File "<stdin>", line 1
    def f(x, y, z): return (z/4.)*(sqrt(x**2+y**2) __gt__ 1 or (z > 2))
```

**Comment by pletzer** [comment]
Fixed by replacing **gt** and other operators by '>' in icqShapeManager.
