### ISSUE TITLE
Seg fault encountered when adding texture

### ISSUE THREAD

**Issue by pletzer** [gregvonkuster/galaxy-csg#31]
```
/var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/database/job_working_directory/000/31/tool_script.sh: line 2: 131996 Segmentation fault      (core dumped) python /var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/tools/csg/icqsol_add_texture.py --input "/var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/database/files/000/dataset_28.dat" --input_file_format_and_type vtkascii --input_dataset_type POLYDATA --input_texture "/var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/database/files/000/dataset_29.dat" --input_texture_file_format jpg --output "/var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/database/files/000/dataset_33.dat" --output_vtk_type vtkascii
```

[data.zip](https://github.com/gregvonkuster/galaxy-csg/files/81784/data.zip)

**Comment by pletzer** [comment]
I was able to reproduce the problem locally...

$ python ~/galaxy-csg/tools/icqsol_add_texture/icqsol_add_texture.py --input "dataset_28.dat" --input_file_format_and_type vtkascii --input_dataset_type POLYDATA --input_texture "dataset_29.dat" --input_texture_file_format jpg --output t.vtk --output_vtk_type vtkascii
/Users/pletzer/anaconda/lib/python2.7/site-packages/icqsol-0.3.4-py2.7.egg/icqsol/shapes/icqShapeManager.py:204: RuntimeWarning: divide by zero encountered in double_scalars
/Users/pletzer/anaconda/lib/python2.7/site-packages/icqsol-0.3.4-py2.7.egg/icqsol/shapes/icqShapeManager.py:205: RuntimeWarning: invalid value encountered in multiply
Traceback (most recent call last):
  File "/Users/pletzer/galaxy-csg/tools/icqsol_add_texture/icqsol_add_texture.py", line 37, in <module>
    texture_file_format=args.input_texture_file_format)
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 233, in addTextureToVtkPolyData
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 212, in getImageIndices
ValueError: cannot convert float NaN to integer

**Comment by pletzer** [comment]
At line 212: 

``` python
j0 = int(d0 * uVec.dot(projectedPoint - startPos))
```

projectedPoint = [nan, nan, nan]

**Comment by pletzer** [comment]
Fixed as of icqsol 0.3.6. This case runs locally on mac os x but still throws a seg fault on linux/openshift

**Comment by pletzer** [comment]
Problem is in icqShapeManager (around line 230). max_edge_length = inf

```
    # Refine if need be.
    pdata = self.refineVtkPolyData(vtk_poly_data,
                                   max_edge_length=max_edge_length)

    # set the colors from the texture file
    rgbArray = vtk.vtkUnsignedCharArray()
    rgbArray.SetNumberOfComponents(3)
    numPoints = pdata.GetNumberOfPoints()
    rgbArray.SetNumberOfTuples(numPoints)
    rgbArray.SetName('Colors')
    point_data_array = imageData.GetPointData().GetArray(0)
    for i in range(numPoints):
        xyz = pdata.GetPoint(i)
        i0, i1 = getImageIndices(xyz)
        rgba = point_data_array.GetTuple(i0 + n0*i1)
        rgbArray.SetTuple(i, rgba[:3])

    pdata.GetPointData().SetScalars(rgbArray)
```

**Comment by pletzer** [comment]
getImageIndices is buggy:

i0, i1 =  968 1004  n0 =  800  n1 =  600  i0 + n0*i1 =  804168

**Comment by pletzer** [comment]
Fixed.
