### ISSUE TITLE
Latest installation recipe results in an error when executing tools

### ISSUE THREAD

**Issue by gregvonkuster** [gregvonkuster/galaxy-csg#6]
@pletzer I'm seeing this when I execute a tool:

Traceback (most recent call last):
  File "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_create_shape/0c73e9f5d877/icqsol_create_shape/icqsol_create_shape.py", line 6, in <module>
    from icqsol.shapes.icqShapeManager import ShapeManager
  File "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/50d175fd15b8/lib/python2.7/site-packages/icqsol/shapes/icqShapeManager.py", line 16, in <module>
    from icqsol.shapes.icqRefineSurface import RefineSurface
  File "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/50d175fd15b8/lib/python2.7/site-packages/icqsol/shapes/icqRefineSurface.py", line 6, in <module>
    import triangle
  File "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/50d175fd15b8/lib/python2.7/site-packages/triangle.py", line 4, in <module>
    import node
ImportError: No module named node

**Comment by pletzer** [comment]
Greg,

Thanks for noticing the problem. I fixed pytriangle.

--Alex

On Mon, Oct 12, 2015 at 1:10 PM, Greg Von Kuster notifications@github.com
wrote:

> @pletzer https://github.com/pletzer I'm seeing this when I execute a
> tool:
> 
> Traceback (most recent call last):
> File
> "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_create_shape/0c73e9f5d877/icqsol_create_shape/icqsol_create_shape.py",
> line 6, in
> from icqsol.shapes.icqShapeManager import ShapeManager
> File
> "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/50d175fd15b8/lib/python2.7/site-packages/icqsol/shapes/icqShapeManager.py",
> line 16, in
> from icqsol.shapes.icqRefineSurface import RefineSurface
> File
> "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/50d175fd15b8/lib/python2.7/site-packages/icqsol/shapes/icqRefineSurface.py",
> line 6, in
> import triangle
> File
> "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/50d175fd15b8/lib/python2.7/site-packages/triangle.py",
> line 4, in
> import node
> ImportError: No module named node
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gregvonkuster/galaxy-csg/issues/6.

## 

Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by gregvonkuster** [comment]
Ok, this is now fixed!  Thanks @pletzer
